//  CHALLENGE (taken from Project Euler, no. 2):
//
//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
//  the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
//  even-valued terms.
//
//  SOLUTION: This version uses in-place variable substitution for memoization.

function sumEvenFibonacci(max) {
    let a = 1;
    let b = 2;
    let sum = b;
    let temp = 0;

    while(a + b <= max){
        temp = a + b;
        a = b;
        b = temp;
        
        if(temp % 2 === 0){
            sum += temp;
        }
    }

    return sum;
}

console.log(sumEvenFibonacci(4000000));
